# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-30 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_auto_20170817_1329'),
        ('post_office', '0004_auto_20160607_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Related site object.', null=True, related_name='attachments', to='sites.Site', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='email',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Related site object.', null=True, related_name='emails', to='sites.Site', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Related site object.', null=True, related_name='emailtemplates', to='sites.Site', verbose_name='Site'),
        ),
    ]
