# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-11-07 07:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0007_auto_20170731_1342'),
        ('post_office', '0005_auto_20180130_0655'),
    ]

    operations = [
    ]
